### ISSUE TITLE
WordPress plugin auto-update not enabled

### ISSUE THREAD

**Issue by amedee** [amedee/ansible-servers#197]
This code in [roles](https://github.com/amedee/ansible-servers/tree/main/roles)/[blog](https://github.com/amedee/ansible-servers/tree/main/roles/blog)/[tasks](https://github.com/amedee/ansible-servers/tree/main/roles/blog/tasks)/[wordpress_plugins_install.yml](https://github.com/amedee/ansible-servers/blob/main/roles/blog/tasks/wordpress_plugins_install.yml) does not actually enable plugins, because `rc == 0`.

```yaml
- name: Check the status of auto-updates for {{ wp_plugin }}
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - plugin
      - auto-updates
      - status
      - "{{ wp_plugin }}"
      - "--path={{ webserver_directory }}"
  changed_when: false
  failed_when: false
  register: wp_plugin_auto_updates

- name: Enables the auto-updates for {{ wp_plugin }}
  when: wp_plugin_auto_updates.rc | int != 0
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - plugin
      - auto-updates
      - enable
      - "{{ wp_plugin }}"
      - "--path={{ webserver_directory }}"
  changed_when: true
```

debug output:
```yaml
  cmd:
  - wp
  - plugin
  - auto-updates
  - status
  - activitypub
  - --path=/var/www/html
  delta: '0:00:01.239732'
  end: '2025-04-30 10:46:28.343598'
  failed_when_result: false
  invocation:
    module_args:
      _raw_params: null
      _uses_shell: false
      argv:
      - wp
      - plugin
      - auto-updates
      - status
      - activitypub
      - --path=/var/www/html
      chdir: null
      creates: null
      executable: null
      expand_argument_vars: true
      removes: null
      stdin: null
      stdin_add_newline: true
      strip_empty_ends: true
  msg: ''
  rc: 0
  start: '2025-04-30 10:46:27.103866'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    name    status
    activitypub     disabled
  stdout_lines: <omitted>
```

Carefully read docs https://developer.wordpress.org/cli/commands/plugin/auto-updates/status/
